### ISSUE TITLE
Proposed role: debops.hhvm

### ISSUE THREAD

**Issue by jbackman** [debops/debops-playbooks#194]
HHVM, or the HipHop Virtual Machine, is a virtual machine for PHP developed by Facebook to improve the performance of PHP applications. Unlike the regular PHP runtime, HHVM uses a just-in-time compiler to convert scripts into native machine code. As a result, third-party benchmarks have shown as much as a 3x load time reduction over PHP-FPM 5.4 for tasks like loading a regular Drupal website.
Read more at: https://www.vultr.com/docs/installing-hhvm-and-nginx-apache-on-ubuntu-debian-mint

**Comment by Gomez** [comment]
AFAIK PHP7 will improve the performance a lot. Maybe its easier to focus on PHP7?

**Comment by drybjed** [comment]
The good news is, `hhvm` package [is available in Sid](https://packages.debian.org/sid/hhvm). The bad news is, it seems to have [many bugs](https://packages.qa.debian.org/h/hhvm.html) and has not yet entered into Testing. I imagine it will be a while when it is available in `jessie-backports`, if ever due to all the transitions in Stretch.

Of course there's also [upstream .deb repository](https://github.com/facebook/hhvm/wiki/Prebuilt-Packages-on-Debian-7) with releases for Wheezy and Jessie, so we could go that route, however I would prefer to use Debian version as soon as it's available.

The other matter is support in different DebOps roles that rely on `php5-fpm`. However, since I'm warming up to the idea of [dropping role dependencies from roles and moving them to playbooks](https://github.com/debops/debops-playbooks/issues/192), it would be easier to do after that. But transition will take a while (busy month at work ahead), so please be patient. :-)

**Comment by ypid** [comment]
@carlalexander already wrote a role which uses upstream packages. https://github.com/carlalexander/debops-wordpress/tree/master/roles/hhvm

For the inpatient once, you can go with this for now :smile:

**Comment by ypid** [comment]
Can be closed in favor to PHP7.
