### ISSUE TITLE
Shouldn’t debops.apt be run earlier in the common.yml playbook?

### ISSUE THREAD

**Issue by ypid** [debops/debops-playbooks#263]
https://github.com/debops/debops-playbooks/blob/master/playbooks/common.yml

Basically after `debops.apt_preferences` and `debops.pki` or am I missing something?

Background is to use a possible configured APT proxy as early as possible (currently configured by `debops.apt`).

**Comment by drybjed** [comment]
I think that `debops.apt` was placed in this order when it used other roles as dependencies way back when it set up `apt-cacher-ng`. Nevermind. It doesn't now, so it should be able to be run earlier.

I would put it after `debops.pki` which handles `ca-certificates` among other things, so that `https://` APT repositories can be accessed.
