### ISSUE TITLE
debops inserts wrong/faulty apt sources (Ansible ppa) on xenial

### ISSUE THREAD

**Issue by chibacityblues** [debops/debops-playbooks#382]
When I ran `debops` on a clean Ubuntu Server 16.04 installation, the playbook stopped at 
`TASK [debops.apt : Update APT cache]`
`fatal: [node6.de]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}`

Running `apt update` manually shows the faulty entries:

`Err:15 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial-updates Release
  404  Not Found`
`Err:16 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial-backports Release
  404  Not Found`

**Comment by drybjed** [comment]
DebOps doesn't add Ansible PPA entries to APT. At least, not by default.

Did you create the Ansible PPA entries in `/etc/apt/sources.list` file? Put them in a separate file, in `/etc/apt/sources.list.d/`. The `debops.apt` role scans the original `sources.list` file to get the package mirrors the host is using, if the Ansible PPA made its way there, it will be wrongly interpreted. This probably should be fixed in the future though, but not just yet.

If the entry was added by your VPS provider, then you should remove it before deploying DebOps.

**Comment by chibacityblues** [comment]
You're right, I found my mistake. Thank you!
